apiVersion: v1
kind: Pod
metadata:
  name: environment-variables-example
  labels:
    application: frontend
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: APPLICATION_TYPE
      value: "Frontend"