apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: pod-label-verify-webhook
webhooks:
  - name: webhook-server.webhooks.svc
    clientConfig:
      service:
        name: webhook-server
        namespace: webhooks
        path: "/validate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM0akNDQWNvQ0NRQ1RhSXd5V1E0MDR6QU5CZ2txaGtpRzl3MEJBUXNGQURBek1URXdMd1lEVlFRRERDaE4KZFhSaGRHbHVaeUJCWkcxcGMzTnBiMjRnUTI5dWRISnZiR3hsY2lCWFpXSm9iMjlySUVOQk1CNFhEVEU1TURneQpNREUxTWpVek5Wb1hEVEU1TURreE9URTFNalV6TlZvd016RXhNQzhHQTFVRUF3d29UWFYwWVhScGJtY2dRV1J0CmFYTnphVzl1SUVOdmJuUnliMnhzWlhJZ1YyVmlhRzl2YXlCRFFUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQUQKZ2dFUEFEQ0NBUW9DZ2dFQkFNN3N5a0tRdW42MjVGMVlXS1R3ZEJZQmRqUUJMYTNzanArNXQzUzFFbXl1dEp2cQo5aitsQmRVWDdKZTRYSUlPNU9LS3gvc01zc3BOYVh4NHpFMmNJYXBRYngrczliMG5OaCtvcmtNVmdHRWU3UCtrCitGSWd6YklFOHBUU2krM3hEdGxqYU54aVBCWjBjL1RMcldvQWJmNVNSY0VUL05PWC9UbUdWR0t2aDJDZkRrT2kKTFRGa0lwS1BHZXpibjdDVUptTGhPOVFDYURNN21PKzB2VVh1Sk5yUjA3aUdDcEplWWxsRitPNzZLdDJybzUzVgpBa21nT1cwRE5hc3J2M094MVk3UVJSY2wyNDBlL3pTenFMenhVWG90TUsxUUhkbHU2dkszKzZUSzN4OFZwS2wrClg1emZVVlpvRm8zWVBUSFk0aktrM1ZKODVNbTFCOFFsOHUvTjMzOENBd0VBQVRBTkJna3Foa2lHOXcwQkFRc0YKQUFPQ0FRRUFxNzY4L0ROR1AzNjFNUUw3cVlpT09OTVNiWWFaRDIrOFl6Y0p0b2x0cnhNRWI3YndaV2pwSWdDVwpOaFMya2ROUWVQMEhrM0xiaUVvQWZnZ09icUsvZjlZNHJXd0swUC8vYlVycDR0OEwxai9Cc3p4VkhaYk5UV3RiClY5NjByQXA4NjkzY2lYRGgyMldnR3ZyOVZTVWx5ZU9lZWMwVjhTRk43K0kyVER4WkRmdHVlTlFhKzlNN3FnVUIKbHNsSVpGb3AxSXVHRnVsRUt1emgrOU1ibVU2ZDNIdDVzRENyRW9Jc1c5UnB5Tys1OW9CY1lZL3ZCcmFwNmdGYQowN1FhS2tOQzVROVZ1bGZNVG5HZkcyREE3VDU4SmxWR053enNvVFhQR1BCS08rVmhHeWU3MjA2ZXl2WlVmQVk5CnpjVjlqWEF3M1RwdVdWSU5RVjFGc0s5R1NNazdSZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]