apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: pod-label-verify-webhook
webhooks:
  - name: webhook-server.webhooks.svc
    namespaceSelector:
      matchExpressions:
      - key: applyValidation
        operator: In
        values: ["true","yes", "1"]
  
    clientConfig:
      service:
        name: webhook-server
        namespace: webhooks
        path: "/validate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM0akNDQWNvQ0NRRHNPMFphQ0swMDVUQU5CZ2txaGtpRzl3MEJBUXNGQURBek1URXdMd1lEVlFRRERDaE4KZFhSaGRHbHVaeUJCWkcxcGMzTnBiMjRnUTI5dWRISnZiR3hsY2lCWFpXSm9iMjlySUVOQk1CNFhEVEU1TURneQpNakEwTWpBeU0xb1hEVEU1TURreU1UQTBNakF5TTFvd016RXhNQzhHQTFVRUF3d29UWFYwWVhScGJtY2dRV1J0CmFYTnphVzl1SUVOdmJuUnliMnhzWlhJZ1YyVmlhRzl2YXlCRFFUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQUQKZ2dFUEFEQ0NBUW9DZ2dFQkFLbnVhT1pIcml2TDNIZ3oxbHhrVVdnczY0ei9DVFRVOTRjOGhLTkdNdHdvMGt6SwpxWXR4NnQ5MTIxNWc0Q0dsbE0zM0pEamljd21XRUJWdkNDNWFYbEtDc1d6STlHS1ZtVEFESW80RFpDSXhvaHBNClR5TkhPZUxTbDJlSllYc2V2cEowRnRBSlRJZ0ZkRm52UUlYYUNYUkJyYVdNV3JpUWZnZGsvaThyQzJveWswblEKRElQb3ljVEFBcmlSZ0FvZnBTek9nZnVqc3ZJeEViaDYvMnNRaHY5M25icFFRTWNHKzNkWHVpWjZweTFTRDArYQplSThXRUFoMDQ0MXpaWGRDOEI5OHlndldCWWdoQUN3dUIzdHFKeEdjbzdDZ011NkVWQXZVTFNvSlA3a0VQS3VTCnRtbHYvUm16Vm5PNWx5NkI1Y1BjOGRKYk1WKzROZVNObngxNmc0MENBd0VBQVRBTkJna3Foa2lHOXcwQkFRc0YKQUFPQ0FRRUFpVC96Q0F1dVR6OFhsSlduczIwWGIwSmJGcE4vZDZKN3hUVGp5S0k3SU9rRW9zaUZaSDg3ZDB3NgpYd3JBTnZiR2NIdlhOZHRRTkY3S3ArZ1k1RzFSeFV3V3BEUnpjdVlrOEVWWnJCMDNhM2JDVXl4ejZmRkUxanlUCmcvMmdKSFhVd005Yy92LzhOZ2NNa2ZtdFlLeGErREV6anQ3V2oxbDFUYlVFM3NCK1ZFalVYYWFtZ3pyZEJFRHQKQmhVejhVZE1sUUVONVNEVWtHNlJzTkVlMWJ1dml0cHlYVGdOb0tBZWVQWkU5Rk5NME5lSmJVbVVacWsyejhTNgpDUVRjOUtSU0piR203bGUrV1ptYnByNzJGcG9GbmZhbXdHUDJVODIxOTQ2TWVROXFiRGVwSXNFSURlTXlUeEdOClcxZWdreFVodVdSdTVGbmZkd2ZYT1ZlaEhiMDlwdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        scope: "Namespaced"