apiVersion: v1
kind: Pod
metadata:
  name: application-pod
  namespace: pods-activity
spec:
  restartPolicy: OnFailure
  containers:
    - name: custom-application-container
      image: custom_application_image:latest
      imagePullPolicy: Never
      readinessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 20
        periodSeconds: 10